num1 = 1000
num2 = 300
num3= 1000

print(num1 < num2) #Menor que...
print(num1 > num2) #Mayor que...
print(num3 >= num2) #Mayor o igual que...
print(num2 <= num3) #Menor o igual que...
print(num1 == num3) #Igual que...
print(num1 != num3) #Diferente que...

pal1="Compromiso"
pal2="Compromiso"
pal3="Compromisó"